language: minimal

services: docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose -f docker/docker-compose-build.yml build --parallel

deploy:
  - provider: script
    script: bash ./docker/push-images.sh
    on:
      branch: main
