language: minimal

services: docker

before_install:
  - docker -v
  - docker-compose -v
#   install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - docker-compose -f docker/docker-compose-build.yml build --parallel

deploy:
  - provider: script
    script: bash ./docker/push-images.sh
    on:
      branch: main
  - provider: script
    script: bash ./k8s/script_deploy.sh
    on:
      branch: main
