apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: reverseproxy
  name: reverseproxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverseproxy
    spec:
      containers:
        - image: walterclementsjr/udagram-reverseproxy
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      restartPolicy: Always
