apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api-feed
  name: api-feed
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app.kubernetes.io/name: api-feed
