apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: reverseproxy
  name: reverseproxy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: reverseproxy
