version: "3"

services:
  reverseproxy:
    image: walterclementsjr/udagram-reverseproxy:latest
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - api-user
      - api-feed
  api-user:
    image: walterclementsjr/udagram-api-user:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  api-feed:
    image: walterclementsjr/udagram-api-feed:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  frontend:
    image: walterclementsjr/udagram-frontend:latest
    ports:
      - "8100:80"

  postgres:
    container_name: db
    image: postgres:15.5
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: udagram
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
